//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EEAFormI9Portal.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentCurrent
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public int DocumentStatusId { get; set; }
        public int RepresentativeId { get; set; }
        public int EVerifyStatusId { get; set; }
        public byte[] DateUpdated { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual DocumentStatu DocumentStatu { get; set; }
        public virtual EverifyStatu EverifyStatu { get; set; }
        public virtual Representative Representative { get; set; }
    }
}
