//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EEAFormI9Portal.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentCompleted
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public string DocumentStatusId { get; set; }
        public string RepresentativeId { get; set; }
        public string EVerifyStatusId { get; set; }
        public byte[] DateAdded { get; set; }
    }
}
