//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EEAFormI9Portal.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentStatu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DocumentStatu()
        {
            this.DocumentCurrents = new HashSet<DocumentCurrent>();
            this.DocumentTerminateds = new HashSet<DocumentTerminated>();
        }
    
        public int Id { get; set; }
        public string Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentCurrent> DocumentCurrents { get; set; }
        public virtual DocumentStatu DocumentStatus1 { get; set; }
        public virtual DocumentStatu DocumentStatu1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentTerminated> DocumentTerminateds { get; set; }
    }
}
