//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EEAFormI9Portal.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Notification()
        {
            this.NotificationRecepients = new HashSet<NotificationRecepient>();
        }
    
        public int Id { get; set; }
        public string Body { get; set; }
        public byte[] CreatedDate { get; set; }
        public string SenderId { get; set; }
        public int NotificationTypeId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual NotificationType NotificationType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotificationRecepient> NotificationRecepients { get; set; }
    }
}
