//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EEAFormI9Portal.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class RepresentativeAppointment
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public byte[] AppointmentTime { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public int Zipcode { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Representative Representative { get; set; }
    }
}
